# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Box settings
  config.vm.box = "centos6.6"
  config.vm.box_url = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.0.0/centos-6.6-x86_64.box"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  # Network settings
  config.vm.network "private_network", ip: "192.168.33.10"

  # Provisioning settings
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["./cookbooks", "./site-cookbooks"]
    chef.json = {
      locale: {
        lang: 'ja_JP.utf8',
        lc_all: 'ja_JP.utf8'
      },
      java: {
        install_flavor: 'openjdk',
        jdk_version: 8,
        accept_license_agreement: true 
      },
      maven: {
        version: 3,
        setup_bin: true
      },
      tomcat: {
        base_version: 7,
        deploy_manager_apps: false,
        run_base_instance: false
      }
    }
    chef.run_list = %w[
      recipe[selinux::disabled]
      recipe[locale]
      recipe[git]
      recipe[tomcat]
      recipe[java]
      recipe[maven]
      recipe[testserver-deploy]
    ]
  end
end